### ISSUE TITLE
libcspice not found

### ISSUE THREAD

**Issue by JRock95** [JuliaAstro/SPICE.jl#20]
When trying to run SPICE.jl on my M1 Mac I get the following error

ERROR: InitError: UndefinedValError: libcspice not defined during evaluation of module SPICE

**Comment by giordano** [comment]
Allowing `CPSICE_jll` v67 at https://github.com/JuliaAstro/SPICE.jl/blob/c118d29eab6b660359eb22ca1bfb156254d29fa2/Project.toml#L17 should fix it

**Comment by JRock95** [comment]
This did fix the problem but when running tests, tkvrsn is now failing

**Comment by JRock95** [comment]
Nevermind I guess that's just the version number on cspice

**Comment by helgee** [comment]
Thanks for raising this issue and submitting a PR. I have tagged a new release which includes the fix.
