### ISSUE TITLE
Incorrect doc for reclat

### ISSUE THREAD

**Issue by cekmsu** [JuliaAstro/SPICE.jl#24]
https://github.com/JuliaAstro/SPICE.jl/blob/62323bd2c6fd0514b9b8d9c51e8ba291a3d8e28b/src/r.jl#L192-L193
Must be:
```
- `lon`: Longitude of the point (radians)
- `lat`: Latitude of the point (radians)
```
not planetographic.

**Comment by afossa** [comment]
It should have been fixed with #27
